/**
 * Curated US employers for the bootstrap scrape. Known ATS boards are listed directly; domain-only entries go through
 * discovery (site scan + public ATS API probes). Add rows freely; nothing here is fetched until `scrape -- bootstrap`.
 */
import type { JobSourceKind } from "@prisma/client";
export interface UsCompany { name: string; domain: string; kind?: JobSourceKind; slug?: string }

export const US_COMPANIES: UsCompany[] = [
  { name: "Stripe", domain: "stripe.com", kind: "GREENHOUSE", slug: "stripe" },
  { name: "Airbnb", domain: "airbnb.com", kind: "GREENHOUSE", slug: "airbnb" },
  { name: "Figma", domain: "figma.com", kind: "GREENHOUSE", slug: "figma" },
  { name: "Datadog", domain: "datadoghq.com", kind: "GREENHOUSE", slug: "datadog" },
  { name: "Cloudflare", domain: "cloudflare.com", kind: "GREENHOUSE", slug: "cloudflare" },
  { name: "Coinbase", domain: "coinbase.com", kind: "GREENHOUSE", slug: "coinbase" },
  { name: "Discord", domain: "discord.com", kind: "GREENHOUSE", slug: "discord" },
  { name: "DoorDash", domain: "doordash.com", kind: "GREENHOUSE", slug: "doordashusa" },
  { name: "Duolingo", domain: "duolingo.com", kind: "GREENHOUSE", slug: "duolingo" },
  { name: "GitLab", domain: "gitlab.com", kind: "GREENHOUSE", slug: "gitlab" },
  { name: "MongoDB", domain: "mongodb.com", kind: "GREENHOUSE", slug: "mongodb" },
  { name: "Robinhood", domain: "robinhood.com", kind: "GREENHOUSE", slug: "robinhood" },
  { name: "Scale AI", domain: "scale.com", kind: "GREENHOUSE", slug: "scaleai" },
  { name: "Vercel", domain: "vercel.com", kind: "GREENHOUSE", slug: "vercel" },
  { name: "Anduril", domain: "anduril.com", kind: "GREENHOUSE", slug: "anduril" },
  { name: "Brex", domain: "brex.com", kind: "GREENHOUSE", slug: "brexinc" },
  { name: "Lyft", domain: "lyft.com", kind: "GREENHOUSE", slug: "lyft" },
  { name: "Pinterest", domain: "pinterest.com", kind: "GREENHOUSE", slug: "pinterest" },
  { name: "Reddit", domain: "redditinc.com", kind: "GREENHOUSE", slug: "reddit" },
  { name: "Asana", domain: "asana.com", kind: "GREENHOUSE", slug: "asana" },
  { name: "Dropbox", domain: "dropbox.com", kind: "GREENHOUSE", slug: "dropbox" },
  { name: "Instacart", domain: "instacart.com", kind: "GREENHOUSE", slug: "instacart" },
  { name: "Flexport", domain: "flexport.com", kind: "GREENHOUSE", slug: "flexport" },
  { name: "Samsara", domain: "samsara.com", kind: "GREENHOUSE", slug: "samsara" },
  { name: "Gusto", domain: "gusto.com", kind: "GREENHOUSE", slug: "gusto" },
  { name: "Affirm", domain: "affirm.com", kind: "GREENHOUSE", slug: "affirm" },
  { name: "Chime", domain: "chime.com", kind: "GREENHOUSE", slug: "chime" },
  { name: "Anthropic", domain: "anthropic.com", kind: "GREENHOUSE", slug: "anthropic" },
  { name: "Databricks", domain: "databricks.com", kind: "GREENHOUSE", slug: "databricks" },
  { name: "Roblox", domain: "roblox.com", kind: "GREENHOUSE", slug: "roblox" },
  { name: "HashiCorp", domain: "hashicorp.com", kind: "GREENHOUSE", slug: "hashicorp" },
  { name: "Elastic", domain: "elastic.co", kind: "GREENHOUSE", slug: "elastic" },
  { name: "Twilio", domain: "twilio.com", kind: "GREENHOUSE", slug: "twilio" },
  { name: "Zapier", domain: "zapier.com", kind: "GREENHOUSE", slug: "zapier" },
  { name: "Webflow", domain: "webflow.com", kind: "GREENHOUSE", slug: "webflow" },
  { name: "Carta", domain: "carta.com", kind: "GREENHOUSE", slug: "carta" },
  { name: "Benchling", domain: "benchling.com", kind: "GREENHOUSE", slug: "benchling" },
  { name: "Faire", domain: "faire.com", kind: "GREENHOUSE", slug: "faire" },
  { name: "Block", domain: "block.xyz", kind: "GREENHOUSE", slug: "block" },
  { name: "Okta", domain: "okta.com", kind: "GREENHOUSE", slug: "okta" },
  { name: "Plaid", domain: "plaid.com", kind: "LEVER", slug: "plaid" },
  { name: "Rippling", domain: "rippling.com", kind: "LEVER", slug: "rippling" },
  { name: "Netlify", domain: "netlify.com", kind: "LEVER", slug: "netlify" },
  { name: "Palantir", domain: "palantir.com", kind: "LEVER", slug: "palantir" },
  { name: "Notion", domain: "notion.so", kind: "ASHBY", slug: "notion" },
  { name: "Linear", domain: "linear.app", kind: "ASHBY", slug: "linear" },
  { name: "Ramp", domain: "ramp.com", kind: "ASHBY", slug: "ramp" },
  { name: "OpenAI", domain: "openai.com", kind: "ASHBY", slug: "openai" },
  { name: "Supabase", domain: "supabase.com", kind: "ASHBY", slug: "supabase" },
  { name: "Retool", domain: "retool.com", kind: "ASHBY", slug: "retool" },
  { name: "Vanta", domain: "vanta.com", kind: "ASHBY", slug: "vanta" },
  { name: "Modal", domain: "modal.com", kind: "ASHBY", slug: "modal" },
  { name: "Perplexity", domain: "perplexity.ai" },
  { name: "Cursor", domain: "cursor.com" },
  { name: "NVIDIA", domain: "nvidia.com" },
  { name: "Apple", domain: "apple.com" },
  { name: "Microsoft", domain: "microsoft.com" },
  { name: "Amazon", domain: "amazon.jobs" },
  { name: "Meta", domain: "meta.com" },
  { name: "Netflix", domain: "netflix.com" },
  { name: "Uber", domain: "uber.com" },
  { name: "Salesforce", domain: "salesforce.com" },
  { name: "Adobe", domain: "adobe.com" },
  { name: "Intuit", domain: "intuit.com" },
  { name: "PayPal", domain: "paypal.com" },
  { name: "Snap", domain: "snap.com" },
  { name: "Zoom", domain: "zoom.com" },
  { name: "ServiceNow", domain: "servicenow.com" },
  { name: "Workday", domain: "workday.com" },
  { name: "CrowdStrike", domain: "crowdstrike.com" },
  { name: "Snowflake", domain: "snowflake.com" },
  { name: "Atlassian", domain: "atlassian.com" },
  { name: "Slack", domain: "slack.com" },
  { name: "Square", domain: "squareup.com" },
  { name: "Etsy", domain: "etsy.com" },
  { name: "Peloton", domain: "onepeloton.com" },
  { name: "Wayfair", domain: "wayfair.com" },
  { name: "Chewy", domain: "chewy.com" },
  { name: "Zillow", domain: "zillow.com" },
  { name: "Redfin", domain: "redfin.com" },
  { name: "Opendoor", domain: "opendoor.com" },
  { name: "SoFi", domain: "sofi.com" },
  { name: "Marqeta", domain: "marqeta.com" },
  { name: "Toast", domain: "toasttab.com" },
  { name: "HubSpot", domain: "hubspot.com" },
  { name: "Klaviyo", domain: "klaviyo.com" },
  { name: "Braze", domain: "braze.com" },
  { name: "Amplitude", domain: "amplitude.com" },
  { name: "Mixpanel", domain: "mixpanel.com" },
  { name: "PagerDuty", domain: "pagerduty.com" },
  { name: "Splunk", domain: "splunk.com" },
  { name: "New Relic", domain: "newrelic.com" },
  { name: "Confluent", domain: "confluent.io" },
  { name: "Cockroach Labs", domain: "cockroachlabs.com" },
  { name: "PlanetScale", domain: "planetscale.com" },
  { name: "Postman", domain: "postman.com" },
  { name: "Grammarly", domain: "grammarly.com" },
  { name: "Canva", domain: "canva.com" },
  { name: "Miro", domain: "miro.com" },
  { name: "Airtable", domain: "airtable.com" },
  { name: "Loom", domain: "loom.com" },
  { name: "Calendly", domain: "calendly.com" },
  { name: "Docusign", domain: "docusign.com" },
  { name: "Box", domain: "box.com" },
  { name: "Twitch", domain: "twitch.tv" },
  { name: "Spotify", domain: "spotify.com" },
  { name: "Epic Games", domain: "epicgames.com" },
  { name: "Unity", domain: "unity.com" },
  { name: "Riot Games", domain: "riotgames.com" },
  { name: "Waymo", domain: "waymo.com" },
  { name: "Cruise", domain: "getcruise.com" },
  { name: "Rivian", domain: "rivian.com" },
  { name: "Tesla", domain: "tesla.com" },
  { name: "SpaceX", domain: "spacex.com" },
  { name: "Relativity Space", domain: "relativityspace.com" },
  { name: "Moderna", domain: "modernatx.com" },
  { name: "Tempus", domain: "tempus.com" },
  { name: "Oscar Health", domain: "hioscar.com" },
  { name: "Ro", domain: "ro.co" },
  { name: "Hims & Hers", domain: "forhims.com" },
  { name: "Capital One", domain: "capitalone.com" },
  { name: "American Express", domain: "americanexpress.com" },
  { name: "JPMorgan Chase", domain: "jpmorganchase.com" },
  { name: "Goldman Sachs", domain: "goldmansachs.com" },
  { name: "Two Sigma", domain: "twosigma.com" },
  { name: "Jane Street", domain: "janestreet.com" },
  { name: "Citadel", domain: "citadel.com" },
  { name: "Hudson River Trading", domain: "hudsonrivertrading.com" },
  { name: "Walmart", domain: "walmart.com" },
  { name: "Target", domain: "target.com" },
  { name: "Nike", domain: "nike.com" },
  { name: "Disney", domain: "disney.com" },
  { name: "Warner Bros. Discovery", domain: "wbd.com" },
  { name: "The New York Times", domain: "nytimes.com" },
  { name: "Duolingo", domain: "duolingo.com", kind: "GREENHOUSE", slug: "duolingo" },
];
