import { readFile } from "node:fs/promises";
import path from "node:path";
import { NormalizedJobSchema, type NormalizedJob } from "@foothold/shared";
import type { SourceAdapter } from "./index";

/** Development dataset: data/seed/jobs.json (generated by `npm run db:seed`, see data/seed/README). */
export const seed: SourceAdapter = {
  kind: "SEED", label: "Seed dataset", needsKey: false,
  async fetchJobs({ slug }) {
    const file = path.resolve(process.cwd(), "../../data/seed", slug.endsWith(".json") ? slug : `${slug}.json`);
    const raw = JSON.parse(await readFile(file, "utf8")) as unknown[];
    return raw.map((r) => NormalizedJobSchema.parse(r) as NormalizedJob);
  },
};
