/**
 * Canonical skill taxonomy. `aliases` are matched case-insensitively at word boundaries.
 * `rx` entries are hand-written regexes for ambiguous short names (Go, R, C).
 * `implies` is used by MATCHING ONLY (Next.js counts as React experience); it is never used
 * to justify new claims in generated resume text.
 */
export type SkillCategory = "LANGUAGE" | "FRAMEWORK" | "TOOL" | "CLOUD" | "DATA" | "DESIGN" | "PRODUCT" | "SOFT" | "DOMAIN" | "OTHER";

export interface SkillDef {
  canonical: string;
  category: SkillCategory;
  aliases?: string[];
  rx?: RegExp;
  implies?: string[];
}

const L = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "LANGUAGE", aliases, implies });
const F = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "FRAMEWORK", aliases, implies });
const T = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "TOOL", aliases, implies });
const C = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "CLOUD", aliases, implies });
const D = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "DATA", aliases, implies });
const G = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "DESIGN", aliases, implies });
const P = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "PRODUCT", aliases, implies });
const S = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "SOFT", aliases, implies });
const M = (canonical: string, aliases: string[] = [], implies: string[] = []): SkillDef => ({ canonical, category: "DOMAIN", aliases, implies });

export const SKILLS: SkillDef[] = [
  // ---- Languages
  L("JavaScript", ["js", "ecmascript", "es6", "es2015+", "vanilla js"]),
  L("TypeScript", ["ts"], ["JavaScript"]),
  L("Python", ["python3", "python 3"]),
  L("Java", ["java 8", "java 11", "java 17", "java 21", "core java"]),
  L("C++", ["cpp", "c plus plus"]),
  L("C#", ["csharp", "c-sharp", "c sharp"]),
  { canonical: "C", category: "LANGUAGE", rx: /(?<![\w+#./-])C(?=[,/)]|\s(?:programming|language)\b)/ },
  { canonical: "Go", category: "LANGUAGE", aliases: ["golang"], rx: /(?<![\w-])Go(?=[\s,./)]|$)(?!\s+(?:to|for|through|live|beyond|ahead|back|out|the|over|up|down|get|see|do|make|find|figure)\b)/m },
  L("Rust", ["rustlang"]),
  L("Ruby"),
  L("PHP"),
  L("Swift"),
  L("Kotlin"),
  L("Scala"),
  { canonical: "R", category: "LANGUAGE", aliases: ["r programming", "r language", "rstudio", "r studio"], rx: /(?<![\w])R(?=[,/)]|\s(?:programming|language|studio|shiny|markdown)\b)/ },
  L("MATLAB"),
  L("Objective-C", ["objective c", "objc"]),
  L("Dart"),
  L("Elixir"),
  L("Erlang"),
  L("Haskell"),
  L("Clojure"),
  L("Perl"),
  L("Lua"),
  L("Bash", ["shell scripting", "shell script", "bash scripting", "unix shell", "zsh"]),
  L("PowerShell"),
  L("SQL", ["structured query language", "t-sql", "pl/sql", "plsql", "ansi sql"]),
  L("HTML", ["html5"]),
  L("CSS", ["css3", "sass", "scss", "less"]),
  L("Solidity"),
  L("Julia"),
  L("Groovy"),
  L("Assembly", ["assembly language", "x86 assembly", "arm assembly"]),
  L("VBA", ["visual basic for applications", "excel vba"]),
  L("SAS"),
  L("COBOL"),
  L("Fortran"),
  L("GraphQL", ["graph ql"], ["API Design"]),
  // ---- Frameworks & runtimes
  F("React", ["react.js", "reactjs", "react js", "react hooks"], ["JavaScript"]),
  F("Next.js", ["nextjs", "next js", "next.js 13", "next.js 14", "next.js 15"], ["React"]),
  F("Vue", ["vue.js", "vuejs", "vue 3"], ["JavaScript"]),
  F("Nuxt", ["nuxt.js", "nuxtjs"], ["Vue"]),
  F("Angular", ["angularjs", "angular.js", "angular 2+"], ["TypeScript"]),
  F("Svelte", ["sveltekit", "svelte kit"], ["JavaScript"]),
  F("Node.js", ["node", "nodejs", "node js"], ["JavaScript"]),
  F("Express", ["express.js", "expressjs"], ["Node.js"]),
  F("NestJS", ["nest.js", "nest js"], ["Node.js", "TypeScript"]),
  F("Django", ["django rest framework", "drf"], ["Python"]),
  F("Flask", [], ["Python"]),
  F("FastAPI", ["fast api"], ["Python"]),
  F("Spring", ["spring boot", "springboot", "spring framework", "spring mvc"], ["Java"]),
  F("Ruby on Rails", ["rails", "ror"], ["Ruby"]),
  F("Laravel", [], ["PHP"]),
  F(".NET", ["dotnet", ".net core", ".net 6", ".net 8", ".net framework"], ["C#"]),
  F("ASP.NET", ["asp.net core", "asp.net mvc"], [".NET", "C#"]),
  F("React Native", ["react-native"], ["React", "Mobile Development"]),
  F("Flutter", [], ["Dart", "Mobile Development"]),
  F("SwiftUI", [], ["Swift", "iOS"]),
  F("UIKit", [], ["Swift", "iOS"]),
  F("Jetpack Compose", ["compose"], ["Kotlin", "Android"]),
  F("Android", ["android sdk", "android development", "android studio"], ["Mobile Development"]),
  F("iOS", ["ios development", "ios sdk", "xcode"], ["Mobile Development"]),
  F("Electron", ["electron.js"], ["JavaScript"]),
  F("Tailwind CSS", ["tailwind", "tailwindcss"], ["CSS"]),
  F("Bootstrap", ["bootstrap 5"], ["CSS"]),
  F("Redux", ["redux toolkit", "rtk"], ["React"]),
  F("REST APIs", ["rest", "restful", "rest api", "restful apis", "restful services", "http apis"], ["API Design"]),
  F("gRPC", ["grpc", "protobuf", "protocol buffers"], ["API Design"]),
  F("WebSockets", ["websocket", "socket.io"], []),
  F("jQuery", [], ["JavaScript"]),
  F("Remix", ["remix.run"], ["React"]),
  F("Gatsby", [], ["React"]),
  F("Storybook", [], ["Frontend Development"]),
  F("Three.js", ["threejs", "webgl"], ["JavaScript"]),
  F("Unity", ["unity3d", "unity 3d"], ["C#", "Game Development"]),
  F("Unreal Engine", ["unreal", "ue4", "ue5"], ["C++", "Game Development"]),
  F("Qt", ["qt framework", "pyqt"], ["C++"]),
  F("Phoenix", ["phoenix framework", "liveview"], ["Elixir"]),
  F("Hibernate", ["jpa", "spring data jpa"], ["Java"]),
  F("Prisma", ["prisma orm"], ["SQL", "TypeScript"]),
  F("TypeORM", [], ["SQL", "TypeScript"]),
  F("Sequelize", [], ["SQL", "Node.js"]),
  F("SQLAlchemy", [], ["SQL", "Python"]),
  F("Pandas", [], ["Python", "Data Analysis"]),
  F("NumPy", ["numpy"], ["Python"]),
  F("SciPy", [], ["Python"]),
  F("scikit-learn", ["sklearn", "scikit learn"], ["Python", "Machine Learning"]),
  F("TensorFlow", ["tensorflow 2", "tf"], ["Python", "Deep Learning"]),
  F("PyTorch", ["torch"], ["Python", "Deep Learning"]),
  F("Keras", [], ["Deep Learning"]),
  F("Hugging Face", ["huggingface", "transformers library"], ["Machine Learning"]),
  F("LangChain", ["langgraph"], ["LLMs"]),
  F("OpenAI API", ["openai", "gpt-4", "gpt-4o", "chatgpt api"], ["LLMs"]),
  F("Anthropic API", ["claude api", "claude"], ["LLMs"]),
  F("Apache Spark", ["spark", "pyspark"], ["Data Engineering"]),
  F("Hadoop", ["hdfs", "mapreduce"], ["Data Engineering"]),
  F("Airflow", ["apache airflow"], ["Data Engineering", "Python"]),
  F("dbt", ["data build tool"], ["SQL", "Data Engineering"]),
  F("Kafka", ["apache kafka", "kafka streams"], ["Message Queues"]),
  F("RabbitMQ", [], ["Message Queues"]),
  F("Flink", ["apache flink"], ["Data Engineering"]),
  F("Matplotlib", [], ["Python", "Data Visualization"]),
  F("Plotly", ["plotly dash"], ["Data Visualization"]),
  F("Seaborn", [], ["Python", "Data Visualization"]),
  F("XGBoost", ["lightgbm", "gradient boosting"], ["Machine Learning"]),
  F("MLflow", [], ["MLOps"]),
  F("CUDA", [], ["C++"]),
  // ---- Tools & platforms
  T("Git", ["git version control", "version control"]),
  T("GitHub", [], ["Git"]),
  T("GitLab", ["gitlab ci"], ["Git", "CI/CD"]),
  T("Bitbucket", [], ["Git"]),
  T("Docker", ["docker compose", "containers", "containerization"]),
  T("Kubernetes", ["k8s", "kubectl"], ["Docker"]),
  T("Terraform", [], ["Infrastructure as Code"]),
  T("Ansible", [], ["Infrastructure as Code"]),
  T("Pulumi", [], ["Infrastructure as Code"]),
  T("Jenkins", [], ["CI/CD"]),
  T("GitHub Actions", ["github workflows"], ["CI/CD"]),
  T("CircleCI", ["circle ci"], ["CI/CD"]),
  T("ArgoCD", ["argo cd", "argo"], ["Kubernetes", "CI/CD"]),
  T("Helm", ["helm charts"], ["Kubernetes"]),
  T("Linux", ["ubuntu", "debian", "centos", "rhel", "red hat"]),
  T("Nginx", ["apache http server", "reverse proxy"]),
  T("Jira", [], ["Agile"]),
  T("Confluence"),
  T("Postman", ["insomnia"]),
  T("Webpack", ["vite", "rollup", "esbuild", "babel", "bundlers"]),
  T("ESLint", ["prettier", "linting"]),
  T("Jest", [], ["Unit Testing"]),
  T("Vitest", [], ["Unit Testing"]),
  T("Cypress", [], ["End-to-End Testing"]),
  T("Playwright", [], ["End-to-End Testing"]),
  T("Selenium", ["selenium webdriver"], ["End-to-End Testing"]),
  T("Mocha", ["chai"], ["Unit Testing"]),
  T("JUnit", ["junit 5", "mockito", "testng"], ["Unit Testing", "Java"]),
  T("pytest", ["py.test", "unittest"], ["Unit Testing", "Python"]),
  T("Puppeteer", [], ["End-to-End Testing"]),
  T("Grafana", [], ["Observability"]),
  T("Prometheus", [], ["Observability"]),
  T("Datadog", [], ["Observability"]),
  T("Splunk", [], ["Observability"]),
  T("New Relic", ["newrelic"], ["Observability"]),
  T("Sentry", [], ["Observability"]),
  T("PagerDuty", ["on-call", "oncall"], ["Incident Response"]),
  T("Bazel", ["buck"]),
  T("Gradle", [], ["Java"]),
  T("Maven", [], ["Java"]),
  T("npm", ["yarn", "pnpm"], ["Node.js"]),
  T("Jupyter", ["jupyter notebooks", "jupyterlab", "google colab"], ["Python"]),
  T("Salesforce", ["sfdc", "salesforce crm", "apex"]),
  T("SAP", ["sap erp", "sap s/4hana"]),
  T("ServiceNow"),
  T("Tableau", [], ["Data Visualization"]),
  T("Power BI", ["powerbi"], ["Data Visualization"]),
  T("Looker", ["looker studio", "lookml"], ["Data Visualization"]),
  T("Excel", ["microsoft excel", "advanced excel", "pivot tables", "vlookup", "google sheets", "spreadsheets"]),
  T("Google Analytics", ["ga4"], ["Product Analytics"]),
  T("Mixpanel", [], ["Product Analytics"]),
  T("Amplitude", [], ["Product Analytics"]),
  T("Segment", ["segment.io"], ["Product Analytics"]),
  T("PostHog", ["posthog"], ["Product Analytics"]),
  T("HubSpot"),
  T("Zendesk", ["intercom", "freshdesk"]),
  T("Notion"),
  T("Asana", ["trello", "monday.com", "clickup", "linear"]),
  T("Snowflake", [], ["SQL", "Data Warehousing"]),
  T("Databricks", [], ["Apache Spark", "Data Engineering"]),
  T("OpenAPI", ["swagger", "openapi spec"], ["API Design"]),
  T("Auth0", [], ["Authentication"]),
  T("Okta", [], ["Authentication"]),
  T("Stripe", ["stripe api"], ["Payments"]),
  T("Twilio", ["sendgrid"]),
  T("Firebase", ["firestore", "firebase auth"], ["Google Cloud"]),
  T("Supabase", [], ["PostgreSQL"]),
  T("Vercel", ["netlify"]),
  T("Heroku"),
  T("Cloudflare", ["cloudflare workers"]),
  T("LaunchDarkly", ["feature flags", "feature flagging"]),
  T("Optimizely", [], ["A/B Testing"]),
  T("Zapier", ["make.com", "n8n"]),
  T("Airtable"),
  T("Retool"),
  T("Metabase", [], ["Data Visualization"]),
  T("Contentful", ["sanity", "strapi", "headless cms"]),
  T("WordPress", [], ["PHP"]),
  T("Shopify", ["shopify plus", "liquid"], ["E-commerce"]),
  T("Webflow", ["framer sites"]),
  T("Miro", ["figjam", "lucidchart", "whimsical"]),
  T("Elasticsearch", ["elastic search", "opensearch", "elk stack", "elk"], ["Search"]),
  T("Redis", ["memcached"], ["Caching"]),
  T("MongoDB", ["mongo", "mongoose"], ["NoSQL"]),
  T("Cassandra", ["scylladb"], ["NoSQL"]),
  T("Neo4j", ["graph databases", "graph database"]),
  T("Weights & Biases", ["wandb", "weights and biases"], ["MLOps"]),
  T("Vector Databases", ["pgvector", "pinecone", "weaviate", "milvus", "qdrant", "chroma", "vector db", "vector search"], ["Machine Learning"]),
  // ---- Cloud
  C("AWS", ["amazon web services", "aws cloud"]),
  C("Azure", ["microsoft azure", "azure cloud"]),
  C("Google Cloud", ["gcp", "google cloud platform"]),
  C("AWS Lambda", ["lambda"], ["AWS", "Serverless"]),
  C("EC2", ["amazon ec2"], ["AWS"]),
  C("S3", ["amazon s3", "aws s3"], ["AWS"]),
  C("ECS", ["amazon ecs", "fargate"], ["AWS", "Docker"]),
  C("EKS", ["amazon eks"], ["AWS", "Kubernetes"]),
  C("RDS", ["amazon rds", "aurora"], ["AWS", "SQL"]),
  C("DynamoDB", ["dynamo db"], ["AWS", "NoSQL"]),
  C("CloudFormation", ["cloud formation"], ["AWS", "Infrastructure as Code"]),
  C("AWS CDK", ["cdk"], ["AWS", "Infrastructure as Code"]),
  C("Serverless", ["serverless framework", "serverless architecture"]),
  C("Cloud Run", ["gke", "google kubernetes engine"], ["Google Cloud"]),
  C("BigQuery", ["big query"], ["Google Cloud", "SQL"]),
  C("Pub/Sub", ["pubsub", "sqs", "sns", "eventbridge"], ["Message Queues"]),
  C("Azure DevOps", ["azure pipelines"], ["Azure", "CI/CD"]),
  C("Azure Functions", [], ["Azure", "Serverless"]),
  C("OpenShift", [], ["Kubernetes"]),
  C("Redshift", ["amazon redshift"], ["AWS", "SQL", "Data Warehousing"]),
  C("SageMaker", ["amazon sagemaker"], ["AWS", "MLOps"]),
  C("Vertex AI", [], ["Google Cloud", "MLOps"]),
  C("Kinesis", ["amazon kinesis"], ["AWS", "Data Engineering"]),
  C("IAM", ["aws iam", "identity and access management"], ["Cloud Security"]),
  C("VPC", ["networking (vpc)", "virtual private cloud"], ["Networking"]),
  C("CDN", ["cloudfront", "content delivery network"]),
  // ---- Data & ML
  D("PostgreSQL", ["postgres", "postgresql database", "psql"], ["SQL"]),
  D("MySQL", ["mariadb"], ["SQL"]),
  D("SQLite", [], ["SQL"]),
  D("SQL Server", ["mssql", "microsoft sql server", "sql server 2019"], ["SQL"]),
  D("Oracle Database", ["oracle db", "oracle sql"], ["SQL"]),
  D("NoSQL", ["nosql databases", "document databases"]),
  D("Machine Learning", ["ml", "machine-learning", "ml models", "predictive modeling", "predictive models"]),
  D("Deep Learning", ["neural networks", "cnn", "rnn", "transformers"], ["Machine Learning"]),
  D("NLP", ["natural language processing", "text mining"], ["Machine Learning"]),
  D("Computer Vision", ["opencv", "image processing", "object detection"], ["Machine Learning"]),
  D("LLMs", ["large language models", "llm", "generative ai", "genai", "gen ai", "prompt engineering", "foundation models"], ["Machine Learning"]),
  D("RAG", ["retrieval-augmented generation", "retrieval augmented generation"], ["LLMs"]),
  D("MLOps", ["ml ops", "model deployment", "model serving"], ["Machine Learning"]),
  D("Reinforcement Learning", ["rl"], ["Machine Learning"]),
  D("Recommendation Systems", ["recommender systems", "recsys", "personalization"], ["Machine Learning"]),
  D("Time Series Analysis", ["time series", "forecasting models"], ["Statistics"]),
  D("Feature Engineering", [], ["Machine Learning"]),
  D("Data Analysis", ["data analytics", "analytics", "quantitative analysis", "exploratory data analysis", "eda"]),
  D("Data Engineering", ["data pipelines", "data pipeline", "etl", "elt", "etl pipelines"]),
  D("Data Modeling", ["data modelling", "dimensional modeling", "schema design"]),
  D("Data Warehousing", ["data warehouse", "data lake", "lakehouse"]),
  D("Data Visualization", ["data viz", "dashboards", "dashboarding", "reporting"]),
  D("Statistics", ["statistical analysis", "statistical modeling", "hypothesis testing", "regression", "probability"]),
  D("A/B Testing", ["ab testing", "a/b tests", "experimentation", "experiment design", "split testing"], ["Statistics"]),
  D("Big Data", ["large-scale data", "large scale data"], ["Data Engineering"]),
  D("Search", ["search relevance", "information retrieval", "full-text search"]),
  D("Caching", ["cache", "cdn caching"]),
  D("Message Queues", ["message queue", "messaging systems", "event streaming", "pub-sub"], ["Event-Driven Architecture"]),
  D("Data Governance", ["data quality", "data lineage", "master data management"]),
  D("Presto", ["trino", "athena", "hive"], ["SQL"]),
  // ---- Design
  G("Figma", [], ["UI Design"]),
  G("Sketch", [], ["UI Design"]),
  G("Adobe XD", ["xd"], ["UI Design"]),
  G("Photoshop", ["adobe photoshop"], ["Visual Design"]),
  G("Illustrator", ["adobe illustrator"], ["Visual Design"]),
  G("After Effects", ["adobe after effects"], ["Motion Design"]),
  G("Framer", [], ["Prototyping"]),
  G("UX Design", ["ux", "user experience", "user experience design", "ux/ui", "ui/ux"]),
  G("UI Design", ["ui", "user interface design", "interface design"]),
  G("User Research", ["user interviews", "ux research", "customer interviews", "user testing"]),
  G("Wireframing", ["wireframes"]),
  G("Prototyping", ["prototypes", "rapid prototyping", "interactive prototypes"]),
  G("Design Systems", ["design system", "component libraries", "component library"]),
  G("Accessibility", ["a11y", "wcag", "ada compliance", "accessible design", "section 508"]),
  G("Interaction Design", ["ixd"]),
  G("Visual Design", ["graphic design"]),
  G("Usability Testing", ["usability studies"]),
  G("Information Architecture", ["ia"]),
  G("Motion Design", ["animation", "micro-interactions"]),
  G("Typography"),
  G("Canva"),
  G("Adobe Creative Suite", ["creative cloud", "adobe creative cloud", "indesign", "premiere pro"]),
  // ---- Product & business
  P("Product Management", ["product manager", "product owner", "product ownership"]),
  P("Product Strategy", ["product vision"]),
  P("Roadmapping", ["roadmap", "product roadmap", "roadmaps"]),
  P("User Stories", ["backlog grooming", "backlog management", "acceptance criteria"]),
  P("Agile", ["agile methodologies", "agile development", "agile/scrum", "sdlc"]),
  P("Scrum", ["scrum master", "sprint planning", "sprints"], ["Agile"]),
  P("Kanban", [], ["Agile"]),
  P("Stakeholder Management", ["stakeholder communication", "executive communication", "stakeholder alignment"]),
  P("Go-to-Market", ["gtm", "go to market", "product launches", "product launch"]),
  P("Product Analytics", ["funnel analysis", "cohort analysis", "user analytics", "metrics", "kpis", "kpi"]),
  P("OKRs", ["okr", "goal setting"]),
  P("PRDs", ["prd", "product requirements", "product requirements documents", "product specs", "requirements documents"]),
  P("Customer Discovery", ["customer research", "voice of customer", "jobs to be done", "jtbd"]),
  P("Competitive Analysis", ["market analysis", "competitive research"]),
  P("Pricing Strategy", ["pricing", "packaging", "monetization"]),
  P("Growth", ["growth hacking", "growth marketing", "user acquisition", "retention"]),
  P("Project Management", ["pmp", "project planning", "project delivery"]),
  P("Program Management", ["tpm", "technical program management"]),
  P("Requirements Gathering", ["requirements analysis", "business requirements"]),
  P("Market Research", ["market sizing", "tam sam som"]),
  P("Product Marketing", ["positioning", "messaging"]),
  P("Customer Success", ["customer support", "customer service", "account management"]),
  P("Sales", ["b2b sales", "saas sales", "enterprise sales", "inside sales", "cold calling", "pipeline management"]),
  P("Business Development", ["partnerships", "bd", "strategic partnerships"]),
  P("Digital Marketing", ["performance marketing", "paid media", "ppc", "google ads", "meta ads", "facebook ads"]),
  P("SEO", ["search engine optimization", "sem"]),
  P("Content Marketing", ["content strategy", "blogging"]),
  P("Email Marketing", ["lifecycle marketing", "crm marketing", "mailchimp", "klaviyo"]),
  P("Social Media Marketing", ["social media", "community management"]),
  P("Copywriting", ["ux writing", "content writing"]),
  P("Brand Strategy", ["branding", "brand marketing"]),
  P("Financial Modeling", ["financial models", "dcf", "valuation"]),
  P("Financial Analysis", ["fp&a", "variance analysis", "financial reporting"]),
  P("Budgeting", ["budget management", "forecasting", "cost management"]),
  P("Accounting", ["gaap", "bookkeeping", "quickbooks", "cpa"]),
  P("Operations", ["operations management", "business operations", "bizops", "process improvement", "process optimization"]),
  P("Supply Chain", ["logistics", "procurement", "inventory management"]),
  P("Recruiting", ["talent acquisition", "sourcing", "hiring"]),
  P("People Operations", ["human resources", "hr", "hrbp", "onboarding programs"]),
  P("Strategy Consulting", ["management consulting", "consulting", "business strategy", "corporate strategy"]),
  P("Business Analysis", ["business analyst", "process mapping", "gap analysis"]),
  P("Data-Driven Decision Making", ["data-driven", "data driven", "data-informed"]),
  P("Customer Journey Mapping", ["journey mapping", "customer journeys"]),
  P("Technical Writing", ["documentation", "api documentation", "technical documentation"]),
  // ---- Soft skills
  S("Communication", ["communication skills", "verbal communication", "written communication", "interpersonal skills"]),
  S("Leadership", ["team leadership", "people management", "leading teams", "managed a team"]),
  S("Collaboration", ["teamwork", "team player", "cross-functional collaboration", "cross functional", "cross-functional teams"]),
  S("Problem Solving", ["problem-solving", "analytical skills", "analytical thinking"]),
  S("Critical Thinking"),
  S("Time Management", ["prioritization", "organizational skills", "multitasking"]),
  S("Adaptability", ["flexibility", "fast-paced environment", "ambiguity"]),
  S("Mentoring", ["mentorship", "coaching", "mentored"]),
  S("Presentation Skills", ["presentations", "public speaking", "storytelling"]),
  S("Negotiation", ["negotiating", "contract negotiation"]),
  S("Attention to Detail", ["detail-oriented", "detail oriented"]),
  S("Customer Focus", ["customer-centric", "customer obsession", "customer empathy", "user empathy"]),
  S("Conflict Resolution"),
  S("Decision Making", ["decision-making", "judgment"]),
  S("Strategic Thinking", ["strategic planning", "big picture thinking"]),
  S("Ownership", ["bias for action", "self-starter", "self starter", "entrepreneurial", "initiative"]),
  S("Creativity", ["creative thinking", "innovation"]),
  // ---- Domains & engineering practices
  M("Fintech", ["financial technology", "financial services"]),
  M("Healthcare", ["healthtech", "health tech", "medical", "clinical", "ehr", "hl7", "fhir"]),
  M("E-commerce", ["ecommerce", "e commerce", "online retail", "marketplace", "marketplaces"]),
  M("SaaS", ["software as a service", "b2b saas", "b2b software"]),
  M("Cybersecurity", ["security", "infosec", "information security", "application security", "appsec", "security engineering"]),
  M("Blockchain", ["web3", "crypto", "cryptocurrency", "smart contracts", "defi", "ethereum"]),
  M("Gaming", ["video games", "games industry"]),
  M("EdTech", ["education technology", "e-learning", "elearning"]),
  M("AdTech", ["advertising technology", "programmatic advertising", "martech"]),
  M("Payments", ["payment processing", "payment systems", "payment gateways", "billing systems"]),
  M("Insurance", ["insurtech"]),
  M("Banking", ["capital markets", "trading systems", "investment banking", "wealth management"]),
  M("Real Estate", ["proptech"]),
  M("Automotive", ["autonomous vehicles", "self-driving", "adas"]),
  M("Telecommunications", ["telecom", "5g"]),
  M("Biotech", ["bioinformatics", "genomics", "life sciences", "pharma", "pharmaceutical"]),
  M("Government", ["public sector", "civic tech", "federal"]),
  M("Defense", ["aerospace", "dod", "security clearance"]),
  M("Energy", ["cleantech", "climate tech", "renewables", "renewable energy", "utilities"]),
  M("Manufacturing", ["industrial", "industry 4.0"]),
  M("Retail", ["consumer goods", "cpg"]),
  M("Media", ["entertainment", "streaming", "publishing"]),
  M("Legal", ["legaltech", "legal tech", "contracts", "compliance"]),
  M("Nonprofit", ["non-profit", "ngo", "social impact"]),
  M("Hardware", ["pcb", "firmware", "electrical engineering", "fpga", "verilog", "vhdl"]),
  M("Robotics", ["ros", "robot operating system", "motion planning"]),
  M("IoT", ["internet of things", "connected devices", "edge computing"]),
  M("Embedded Systems", ["embedded", "embedded software", "rtos", "microcontrollers", "arm cortex"]),
  M("AR/VR", ["augmented reality", "virtual reality", "xr", "mixed reality", "spatial computing"]),
  M("Regulatory Compliance", ["soc 2", "soc2", "hipaa", "gdpr", "pci dss", "pci-dss", "iso 27001", "sox", "ccpa"]),
  M("Distributed Systems", ["distributed computing", "large-scale systems", "high availability", "fault tolerance", "consensus"]),
  M("Microservices", ["microservice architecture", "service-oriented architecture", "soa"], ["Distributed Systems"]),
  M("System Design", ["systems design", "architecture design", "scalable systems", "scalability"]),
  M("Software Architecture", ["architecture", "technical architecture", "solution architecture", "solutions architect"]),
  M("Event-Driven Architecture", ["event driven", "event sourcing", "cqrs"]),
  M("Networking", ["tcp/ip", "network protocols", "dns", "http/2", "load balancing", "load balancers"]),
  M("Operating Systems", ["os internals", "kernel", "linux kernel", "systems programming"]),
  M("Compilers", ["llvm", "compiler design", "programming languages"]),
  M("Algorithms", ["data structures", "data structures and algorithms", "dsa", "algorithm design", "complexity analysis"]),
  M("Object-Oriented Programming", ["oop", "object oriented", "object-oriented design", "design patterns", "solid principles"]),
  M("Functional Programming", ["fp"]),
  M("Test-Driven Development", ["tdd", "bdd", "behavior-driven development"], ["Unit Testing"]),
  M("Unit Testing", ["unit tests", "automated testing", "test automation", "testing"]),
  M("Integration Testing", ["integration tests"]),
  M("End-to-End Testing", ["e2e testing", "e2e tests", "end to end testing", "browser testing", "ui testing"]),
  M("Load Testing", ["performance testing", "stress testing", "k6", "jmeter", "locust"]),
  M("CI/CD", ["ci cd", "continuous integration", "continuous delivery", "continuous deployment", "build pipelines", "deployment pipelines", "release management"]),
  M("DevOps", ["devops practices", "platform engineering"]),
  M("SRE", ["site reliability engineering", "site reliability", "reliability engineering", "slos", "slas"]),
  M("Infrastructure as Code", ["iac", "infrastructure automation", "configuration management"]),
  M("Observability", ["monitoring", "logging", "tracing", "alerting", "opentelemetry", "metrics and monitoring"]),
  M("Incident Response", ["incident management", "postmortems", "root cause analysis", "rca", "troubleshooting"]),
  M("Performance Optimization", ["performance tuning", "optimization", "profiling", "latency optimization", "web performance"]),
  M("API Design", ["api development", "apis", "api integration", "third-party apis", "api integrations", "web services"]),
  M("Authentication", ["oauth", "oauth2", "oauth 2.0", "openid connect", "oidc", "jwt", "saml", "sso", "single sign-on", "authorization", "rbac"]),
  M("Cryptography", ["encryption", "tls", "pki", "hashing"]),
  M("Penetration Testing", ["pentesting", "pen testing", "ethical hacking", "vulnerability assessment", "vulnerability management", "burp suite", "metasploit"]),
  M("Threat Modeling", ["threat detection", "threat intelligence", "risk assessment"]),
  M("Cloud Security", ["security best practices", "zero trust", "cloud security posture"]),
  M("Network Security", ["firewalls", "vpn", "ids/ips", "siem"]),
  M("Mobile Development", ["mobile apps", "mobile app development", "mobile engineering"]),
  M("Web Development", ["web applications", "web apps", "web application development"]),
  M("Frontend Development", ["front-end", "frontend", "front end", "front-end development", "ui development", "responsive design", "responsive web design"]),
  M("Backend Development", ["back-end", "backend", "back end", "server-side", "server side development"]),
  M("Full-Stack Development", ["full stack", "fullstack", "full-stack"], ["Frontend Development", "Backend Development"]),
  M("Game Development", ["game design", "game engine"]),
  M("Code Review", ["code reviews", "pull requests", "pr reviews"]),
  M("Debugging", ["bug fixing", "defect resolution"]),
  M("Pair Programming", ["mob programming"]),
  M("Localization", ["i18n", "l10n", "internationalization"]),
  M("Progressive Web Apps", ["pwa"]),
  M("Server-Side Rendering", ["ssr", "static site generation", "ssg"]),
  M("WebAssembly", ["wasm"]),
  M("Concurrency", ["multithreading", "multi-threading", "parallel programming", "async programming", "asynchronous programming"]),
  M("Low-Latency Systems", ["low latency", "high-performance computing", "hpc", "high performance"]),
  M("Computer Science Fundamentals", ["cs fundamentals", "computer science"]),
  M("Technical Leadership", ["tech lead", "technical lead", "engineering management", "engineering manager", "staff engineer"]),
  M("Quantitative Research", ["quant", "quantitative finance", "alpha research"]),
  M("Analytics Engineering", ["semantic layer", "metrics layer"], ["dbt", "SQL"]),
];
