export const env = {
  appUrl: process.env.APP_URL ?? process.env.AUTH_URL ?? "http://localhost:3000",
  isProd: process.env.NODE_ENV === "production",
  devLogin: process.env.NODE_ENV !== "production" && process.env.DEV_LOGIN === "true",
  llmMode: (process.env.LLM_MODE ?? "auto") as "auto" | "anthropic" | "heuristic" | "fixture",
  anthropicKey: process.env.ANTHROPIC_API_KEY || null,
  modelMain: process.env.LLM_MODEL_MAIN ?? "claude-opus-5",
  modelBulk: process.env.LLM_MODEL_BULK ?? "claude-haiku-4-5",
  embeddingsProvider: (process.env.EMBEDDINGS_PROVIDER ?? "auto") as "auto" | "voyage" | "openai" | "local",
  voyageKey: process.env.VOYAGE_API_KEY || null,
  openaiKey: process.env.OPENAI_API_KEY || null,
  storageDir: process.env.STORAGE_DIR ?? "./storage",
  jobsMode: (process.env.JOBS_MODE ?? "inline") as "inline" | "queue",
  cronSecret: process.env.CRON_SECRET ?? "dev-cron-secret",
  posthogKey: process.env.NEXT_PUBLIC_POSTHOG_KEY || null,
  posthogHost: process.env.NEXT_PUBLIC_POSTHOG_HOST ?? "https://us.i.posthog.com",
  adzuna: process.env.ADZUNA_APP_ID && process.env.ADZUNA_APP_KEY ? { id: process.env.ADZUNA_APP_ID, key: process.env.ADZUNA_APP_KEY } : null,
  usajobs: process.env.USAJOBS_API_KEY ? { key: process.env.USAJOBS_API_KEY, userAgent: process.env.USAJOBS_USER_AGENT ?? "foothold@example.com" } : null,
};
